app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// Misc. Routes
Route::get('/', 'PostController@index');
Route::post('search', 'UserController@search');
Route::get('erd', function(){
    return View::make('erd');
});
Route::get('docs', function(){
    return View::make('docs');
});

// User Routes
Route::resource('user', 'UserController');
Route::get('register', 'UserController@create');
Route::post('user/login', array('as' => 'user.login', 'uses' => 'UserController@login'));
Route::get('logout', 'UserController@destroy');

// Friend Routes
Route::resource('friendship', 'FriendshipController');
Route::get('unfollow/{id}', 'FriendshipController@destroy');

// Post Routes
Route::resource('post', 'PostController');
Route::get('post/delete/{id}', 'PostController@destroy');

// Comment Routes
Route::resource('comment', 'CommentController');
Route::get('comment={id}/delete', 'CommentController@destroyComment');

app/models/Post.php
<?php

class Post extends Eloquent
{
    // DATABASE TABLE -------------------------------------------------------
    // define which table is used by this model.
    // @var string $table
    protected $table = 'posts';

    // MASS ASSIGNMENT -------------------------------------------------------
    // define which attributes are mass assignable (for security)
    // we only want these 5 attributes able to be filled
    protected $fillable = ['title', 'message', 'user_id', 'privacy'];
    protected $dates = ['created_at', 'updated_at'];

    // DEFINE RELATIONSHIPS --------------------------------------------------

    public function user(){
        return $this->belongsTo('User');
    }

    // each post HAS MANY comments
    public function comments()
    {
        return $this->hasMany('Comment');
    }
}

app/controllers/PostController.php
<?php

class PostController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$posts = Post::orderBy('created_at', 'desc')->get();
        $comments = Comment::all();

        return View::make('home')
            ->with('posts', $posts)
            ->with('comments', $comments);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{

	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
        $rules = array(
            'title'     =>  'required',
            'message'   =>  'required',
            'privacy'   =>  'required'
        );

        // do the validation
        // validate against the inputs from the form
        $validator = Validator::make(Input::all(), $rules);

        // check if the validator failed -----------------------
        if ($validator->fails()) {
            // get the error messages from the validator
            $messages = $validator->messages();

            // refill the form with previous values
            Input::flash();

            // redirect user back to home with the validator errors
            return Redirect::back()
                ->withErrors($validator);
        } else {
            // validation successful ---------------------------
            // submit the post to the database
            Post::create(array(
                'title'    =>  Input::get('title'),
                'message'  =>  Input::get('message'),
                'user_id'  =>  Auth::user()->id,
                'privacy'  => Input::get('privacy')
            ));

            // redirect ----------------------------------------
            // redirect our user back to home so they can do it all over again
            return Redirect::to('/');
        }
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
        $post = Post::find($id);
        $comments = Post::find($id)->comments;

        return View::make('posts.post_detail')
            ->with('post', $post)
            ->with('comments', $comments);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$post = Post::find($id);
		$comments = Post::find($id)->comments;
		return View::make('edit')
			->with('post', $post)
			->with('comments', $comments);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($post_id)
	{
		$rules = array(
			'title'     =>  'required',
			'message'   =>  'required',
			'privacy'   =>  'required'
		);

		$validator = Validator::make(Input::all(), $rules);
		if ($validator->fails()) {
			$messages = $validator->messages();
			Input::flash();
			return Redirect::back()->withErrors($validator);
		} else {
			$post           = Post::find($post_id);
			$post->title    = Input::get('title');
			$post->message  = Input::get('message');
			$post->privacy  = Input::get('privacy');
			$post->save();

			return Redirect::back()->withFlashMessage('Updated Post.');
		}
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
        $comments = Comment::where('post_id','=', $id)->get();
        foreach ($comments as $comment) {
            $comment->delete();
        }
        $post = Post::find($id);
        $post->delete();

		return Redirect::to('/');
	}
	


}

app/views/posts/post_display.blade.php
<br/>
<div class="panel panel-info">
    <!-- Default panel contents -->
    <div class="panel-heading">
        <a href="#">
            <img alt="avatar" width="40" height="40" src="{{{ User::find($post->user_id)->avatar->url() }}}"  class="img-circle">
        </a>
        <strong>{{{ $post->title }}}</strong> by {{{ User::find($post->user_id)->fullName }}}

        <span class="pull-right">
            <a href="{{ URL::route('post.show', array($post->id)) }}"> View</a>
            @if (Auth::check())
                @if(Auth::user()->id == $post->user_id)
                <a href="{{ URL::route('post.edit', array($post->id)) }}"> | Edit</a>
                <a href="{{ URL::to('post/delete/' . $post->id) }}"> | Delete</a>
                @endif
            @endif
        </span>
        <span class="pull-right">{{{ Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $post->created_at)->format('D jS F \a\t G:i') }}} | {{{ $post->privacy }}} |&nbsp;</span>
    </div>
    <div class="panel-body">
        <p>{{{ $post->message }}}</p>
    </div>

    <ul class="list-group">
        @foreach ($comments as $comment)
            @if ($comment->post_id == $post->id)
                <li class="list-group-item">
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="#">
                        <img alt="avatar" width="20" height="20" src="{{{ User::find($post->user_id)->avatar->url() }}}"  class="img-circle">
                    </a>
                    {{{ User::find($comment->user_id)->fullName }}} said {{{ $comment->message }}}
                    <span class="pull-right">{{{ $comment->created_at }}}
                        @if (Auth::id() == $comment->user_id)
                        <a href="{{{ URL::to('comment='.$comment->id.'/delete') }}}">Delete</a>

                        @endif
                    </span>
                </li>
            @endif
        @endforeach

        <!-- New comment -->
        @if(Auth::check())
        <li class="list-group-item">
            {{ Form::open(array('route' => 'comment.store')) }}
            {{ Form::hidden('post_id', $post->id) }}
            {{ Form::textarea('message', '', array('placeholder'=>'Write a comment...','class' => 'form-control', 'rows' => '2')) }}
            {{ Form::submit('Post comment', array('class' => 'btn btn-sm btn-info')) }}
            {{ Form::close() }}
        </li>
        @endif

    </ul>
</div>

app/views/posts/post_form.blade.php
{{ Form::open(array('route' => 'post.store')) }}

<div class="form-group">
    {{ Form::text('title', '', array('placeholder'=>'Post title','class' => 'form-control')) }}
</div>
<div class="form-group">
    {{ Form::textarea('message', '', array('placeholder'=>'Post a story','class' => 'form-control', 'rows' => '4')) }}
</div>
<div>
    {{ Form::select('privacy', array('Public' => 'Public', 'Friends' => 'Friends', 'Private' => 'Private'), 'Private'); }}
    User: <strong>{{{ Auth::user()->fullName }}}</strong>
    {{ Form::submit('Post status', array('class' => 'btn btn-info pull-right m-t-n-xs', 'style' => 'font-weight:600')) }}
</div>

{{ Form::close() }}

app/views/posts/post_update.blade.php
{{ Form::model($post, array('route' => array('post.update', $post->id), 'method' => 'PUT'))  }}

    <div class="form-group">
        {{ Form::text('title', '', array('placeholder'=>'Post title','class' => 'form-control', 'value' => $post->title)) }}
    </div>
    <div class="form-group">
        {{ Form::textarea('message', '', array('placeholder'=>'Post a story','class' => 'form-control', 'rows' => '4', 'value' => $post->message)) }}
    </div>
    <div>
        {{ Form::select('privacy', array('Public' => 'Public', 'Friends' => 'Friends', 'Private' => 'Private'), $post->privacy); }}
         User: <strong>{{{ Auth::user()->fullName }}}</strong>
        {{ Form::submit('Post status', array('class' => 'btn btn-info pull-right m-t-n-xs', 'style' => 'font-weight:600')) }}
    </div>

{{ Form::close() }}