app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// Misc. Routes
Route::get('/', 'PostController@index');
Route::post('search', 'UserController@search');
Route::get('erd', function(){
    return View::make('erd');
});
Route::get('docs', function(){
    return View::make('docs');
});

// User Routes
Route::resource('user', 'UserController');
Route::get('register', 'UserController@create');
Route::post('user/login', array('as' => 'user.login', 'uses' => 'UserController@login'));
Route::get('logout', 'UserController@destroy');

// Friend Routes
Route::resource('friendship', 'FriendshipController');
Route::get('unfollow/{id}', 'FriendshipController@destroy');

// Post Routes
Route::resource('post', 'PostController');
Route::get('post/delete/{id}', 'PostController@destroy');

// Comment Routes
Route::resource('comment', 'CommentController');
Route::get('comment={id}/delete', 'CommentController@destroyComment');

app/views/layouts/alert.blade.php
@if (Session::has('flash_message'))
    <div class="alert alert-success">
        {{ Session::get('flash_message') }}
    </div>
@endif
@if ($errors->has())
    <div class="alert alert-danger">
        @foreach ($errors->all() as $error)
            {{ $error }}<br>
        @endforeach
    </div>
@endif

app/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('title') | AlanBook</title>

    <!-- Bootstrap core CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/styles.css" rel="stylesheet">

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </head>
  
  
    <body>
        <aside>
            @include('layouts.side-nav')
        </aside>
        
        <main>
            
            <div class="jumbotron">
              <div class="container">
                <h1>@yield('title')</h1>

                  {{ Form::open(array('action' => 'UserController@search')) }}

                    {{ Form::text('search', '', array('class' => 'form-control', 'placeholder' => 'Search...')) }}

                  {{ Form::close() }}
              </div>
            </div>
        
        
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                @include('layouts.alert')
                @yield('content')
            </div>
        </div>
            
        </main>
    
    </body>
</html>

app/views/layouts/side-nav.blade.php
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">AlanBook</a>
        </div>
        
        <div id="navbar" class="collapse navbar-collapse">
          
          
          <ul class="nav navbar-nav">

            @if (Auth::check())
            <li {{{ (Request::is('/') ? 'class=active' : '') }}}><a href="/">Home</a></li>
            <li {{{ (Request::is('user/'.Auth::user()->id) ? 'class=active' : '') }}}>
              <a href="{{ URL::route('user.show', array(Auth::user()->id)) }}">Profile</a>
            </li>
            <li><a href="{{ URL::route('friendship.show', array(Auth::user()->id)) }}">Friends</a></li>
            <li><a href="docs">Documentation</a></li>
            <li><a href="erd">ERD</a></li>
            @else
              <li {{{ (Request::is('/') ? 'class=active' : '') }}}><a href="/">Home</a></li>
              <li><a href="#contact">Users</a></li>
              <li><a href="#contact">Documentation</a></li>
              <li><a href="#contact">ERD</a></li>
            @endif
          </ul>
          
          
          @if (Auth::check())
        
            <form class='navbar-form navbar-right'>
              <span style='color:white;'>
                Welcome {{ Auth::user()->fullName }}
              </span>
              
              <a href="{{ URL::to('/logout') }}">
                  <i class="fa fa-sign-out"></i> Log out
              </a>
            </form>
          
          @else
            {{ Form::open(array('route' => 'user.login', 'class' => 'navbar-form navbar-right')) }}
            
            <div class="form-group">
              {{ Form::email('email', '', array('class' => 'form-control', 'placeholder' => 'Email', 'required' => '')) }}
            </div>
            <div class="form-group">
              {{ Form::password('password', array('class' => 'form-control', 'placeholder' => 'Password', 'required' => '')) }}
            </div>
            {{ Form::submit('Sign in', array('class' => 'btn btn-success')) }}
            <a href="{{ URL::to('/register') }}" class="btn btn-danger">Create Account</a>
            
            {{ Form::close() }}
          @endif
          

        </div><!--/.nav-collapse -->
      </div>
</nav>